# Generated by Django 5.0.6 on 2024-06-05 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cocina", "0002_receta_imagen_listadecompras"),
    ]

    operations = [
        migrations.CreateModel(
            name="Desafio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Participacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_participacion", models.DateTimeField(auto_now_add=True)),
                ("votos", models.PositiveIntegerField(default=0)),
                (
                    "desafio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participaciones",
                        to="desafios.desafio",
                    ),
                ),
                (
                    "receta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cocina.receta"
                    ),
                ),
            ],
        ),
    ]
